config/routes.rb
RitlyApp::Application.routes.draw do
  
  get "sessions/new"
  get "sessions/destroy"
  get "users/new"
  get "users/show"
  get "users/create"
  root to: 'site#index'

  resources :users, :sessions

  get '/signup' => 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get'/signin' => 'sessions#new'

  get '/links', to: 'links#index', as: :links

  get '/links/new', to: 'links#new', as: :new_link

  post '/links', to: 'links#create'

  get '/links/:id', to: 'links#show', as: :link

  get 'links/:id/delete', to: 'links#delete'

  get '/go/:code/preview', to: 'links#preview', as: :preview

  get '/go/:code', to: 'links#go', as: :go

end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id          :integer          not null, primary key
#  input_link  :string(255)
#  output_code :string(255)
#  count       :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Link < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  # attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

    private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_filter :signed_in_user, only: [:create, :new, :delete]

  def index
  	@links = Link.all
  end

  def new
  	@link = Link.new
  end

  def create
  	new_params = {}
    input_params = params.require(:link).permit(:input_link)
    new_params[:input_link] = input_params[:input_link]
    new_params[:output_code] = SecureRandom.urlsafe_base64(6)
    link = Link.create(new_params)
    redirect_to link_path(link.id)
  end

  def show
    id = params[:id]
    @link = Link.find(id)
  end

  def preview
    current_code = params[:code]
  	current_record = Link.find_by output_code: current_code
    current_id = current_record.id
    redirect_to link_path(current_id)
  end

  def go
  	current_code = params[:code]
  	current_record = Link.find_by output_code: current_code
    destination = current_record.input_link
    redirect_to destination
  end

  def delete
    id = params[:id]
    deleted_link = Link.find(id)
    deleted_link.destroy
    redirect_to links_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  include SessionsHelper
  
  def new
  end

  def create
    user=User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to user
    else
      # Create an error message and re-render the signin form.
      flash.now[:error]='Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
      sign_out
      redirect_to root_url
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new()
  end

  def create
    # @user=User.new(params[:user])
    @user=User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      flash[:success] = "Welcome to Ritly!"
      sign_in @user
      redirect_to @user
    else
      render'new'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    render :show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # SessionHelper manages @current_user, that's the user currently
  # signed in.

  # signs in supplied user, called from SessionController
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    # current_user is avilable in controllers and views!
    # This is an is an assignment, which we must define - see below
    # note that next line is a call to setter 'def current_user=(user)' below
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  # Authorization: signed_in_user is called in a before_filter
  # callback in each controller, see books/ingredients/recipe controllers
  # Ensures access to create/edit functions on if signed in.
  def signed_in_user
    unless signed_in?
      # If not signed in, save current location in session object
      # to be able to redirect after successful sign in.
      session[:return_to] = request.url
      # prompt sign in page
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  # signs out user by deleting @current_user and session cookie
  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  # Getter and setter for @current_user
  def current_user=(user)
    @current_user = user
  end

  # if current_user doesn't exist, check session cookie for user session
  # If exists, get the user record that belongs to that session.
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Ritly</title>

        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
          <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
          <%= csrf_meta_tags %>
    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">


    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand" href="#">Project name</a> -->
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Ritly Home</a></li>
            <li><a href="/links/new">Shorten Link</a></li>
            <% if signed_in? %>
              <li><%= link_to "My profile", current_user %></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            <% else %>
              <li><%= link_to "Sign up", signup_path %></li>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>  

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
            <br>
            <br>
            <br>
            <br>

    <div class="span10">
      <%flash.each do|key,value|%>
              <div class="alert alert-<%=key%>"> <%=value%> </div>
      <%end%>

    <%= yield %>

    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/links/index.html.erb
<h3>List of Links and Codes</h3></br>

<table class="table table-hover">

<tr>
  <th>ID</th>
  <th>Input Link</th>
  <th>Output Code</th>

  <th>Created</th>
  <th>Updated</th>
</tr>

<% @links.each do |link| %>

<tr>
  <td><%= link.id %></td>
  <td><a href="<%= link.input_link %>"><%= link.input_link %></a></td>

  <td><a href="/go/<%= link.output_code %>/"><%= link.output_code %></a></td>
  <td><%= link.created_at %></td>

  <td><%= link.updated_at%></td>
  <td><a href="/links/<%= link.id %>/delete"><button class="delete">Delete</button></a></td>
</tr>

<% end %>

</table>

app/views/links/new.html.erb
<div>

Enter URL to be shortened. Be sure to enter the starting 'http://' :
</br>
</br>

<%= form_for @link do |f| %>
    <%= f.text_field :input_link, placeholder: "enter URL" %> <br></br>
    
    <%= f.submit %>
<% end %>

</div>

app/views/links/show.html.erb
<div>

<p>You entered <%= @link.input_link %>.</p>

<p>Your Ritly shortened URL code is <%= @link.output_code %>.</p>

<p>Go to <a href="/go/<%= @link.output_code %>">localhost:3000/go/<%= @link.output_code %></a> to visit your URL.</p>

</div>

app/views/site/index.html.erb
<h1> Welcome to Ritly! </h1>

<p><%= link_to "Shorten a link with Ritly", new_link_path %></p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <% unless @user.errors.count == 0   %>
        <div class="alert alert-error">
          The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
        </ul>
      <% end %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>

     </br>
     <p>Existing user? <%= link_to "Sign in!", signin_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <h3><%= @user.name %></h3>
      <h3><%= @user.email %></h3>
    </section>
  </aside>
</div>